/*=================[DATABASE DESAFIOCSHARP]=================*/
CREATE DATABASE [DesafioCSharp];

/*=================[TABELA PLANS]=================*/
CREATE TABLE [dbo].[PLANS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [varchar](50) NULL,
	[STARTDATE] [datetime] NULL,
	[ENDDATE] [datetime] NULL,
 CONSTRAINT [PK_PLAN] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];

/*=================[TABELA USERS]=================*/
CREATE TABLE [dbo].[USERS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[FIRSTNAME] [varchar](100) NOT NULL,
	[LASTNAME] [varchar](100) NOT NULL,
	[BIRTH] [datetime] NOT NULL,
	[PLANID] [int] NULL,
 CONSTRAINT [PK_USERS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[USERS]  WITH CHECK ADD  CONSTRAINT [FK_PLAN] FOREIGN KEY([PLANID])
REFERENCES [dbo].[PLANS] ([ID])
GO

ALTER TABLE [dbo].[USERS] CHECK CONSTRAINT [FK_PLAN]
GO